### ISSUE TITLE
Warning in magic method from CSSStyleDeclaration

### ISSUE THREAD

**Issue by bwojciak** [TheBitBang/SVGF#3]
PHPUnit shows me excception "Undefined variable: attribute_value" which happen to be wrong variable name in method __get from CSSStyleDeclaration (I believe $attribute_value should be removed from call of call_user_func).

**Comment by lukas-staab** [comment]
Can confirm the warning. I would guess  `$attribute_value` should have been `$attribute_name`
https://github.com/TheBitBang/php-svg-framework-SVGF/blob/683e7acafbffc2d60463df7e60f537fab799eed9/src/css/CSSStyleDeclaration.php#L150

**Comment by xavier-atero** [comment]
Fix committed. Thanks!

**Comment by jloguercio** [comment]
Can you update the release with this fix please?
