### ISSUE TITLE
Warning in CSSStyleDeclaration.php - last array element is empty

### ISSUE THREAD

**Issue by lukas-staab** [TheBitBang/SVGF#4]
https://github.com/TheBitBang/php-svg-framework-SVGF/blob/683e7acafbffc2d60463df7e60f537fab799eed9/src/css/CSSStyleDeclaration.php#L177

The last CSS entry ends with `;` therefore a empty element is in the last loop. Either pop the last element before the loop or continue `if(trim($property) === '') continue;` in the loop

**Comment by xavier-atero** [comment]
Fix committed. Thanks!
